# http://www.appveyor.com/docs/appveyor-yml

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2017

version: "{build}-{branch}"

init:
  - git --version
  - git config --global core.autocrlf false
  - git config --global user.name "AppVeyor"
  - git config --global user.email "appveyor@ci.appveyor.com"

environment:
  matrix:
  - nodejs_version: "10"
  global:
    GITHUB_TOKEN:
      secure: HJyWcgJc5e5ltkNY7zTUnuuGldoVv3SYJTRXTzrV/RnmMVwYqy6rnNagSRbZtnJZ
    GH_TOKEN:
      secure: HJyWcgJc5e5ltkNY7zTUnuuGldoVv3SYJTRXTzrV/RnmMVwYqy6rnNagSRbZtnJZ

matrix:
  fast_finish: true

platform:
  - x64

install:
  - ps: |
      Write-Host "Build directory: " -NoNewLine
      Write-Host $env:APPVEYOR_BUILD_FOLDER -ForegroundColor "Green"
      Write-Host "Build number: " -NoNewLine
      Write-Host $env:APPVEYOR_BUILD_NUMBER -ForegroundColor "Green"
      Write-Host "Branch: " -NoNewLine
      Write-Host $env:APPVEYOR_REPO_BRANCH -ForegroundColor "Green"
      Write-Host "Tag: " -NoNewLine
      Write-Host $env:APPVEYOR_REPO_TAG_NAME -ForegroundColor "Green"
      Write-Host "Commit: " -NoNewLine
      Write-Host $env:APPVEYOR_REPO_COMMIT -ForegroundColor "Green"
      Write-Host "Commit timestamp: " -NoNewLine
      Write-Host $env:APPVEYOR_REPO_COMMIT_TIMESTAMP -ForegroundColor "Green"
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g npm
  - npm --version
  - npm config set loglevel warn
  - npm install

build_script:
  - ps: npm run build
  - ps: mkdir releases
  - ps: $PACKAGE_NAME = node -e "console.log(require('./src/package.json').name)"
  - ps: $PACKAGE_VERSION = node -e "console.log(require('./src/package.json').version)"
  - ps: $COMMIT_LOG = git log -1 --format='%ci %H %s'
  - ps: $RELEASE = "${PACKAGE_NAME}-${PACKAGE_VERSION}"
  - ps: echo "$RELEASE"
  - ps: echo "$COMMIT_LOG"
  - ps: |
      if ($env:platform -eq 'x64') {
        npm run build:win-x64
        Get-ChildItem output
        Copy-Item "output\${PACKAGE_NAME} Setup ${PACKAGE_VERSION}.exe" "releases\${RELEASE}-win-x64.exe"
      }
  - ps: |
      if ($env:platform -eq 'x64') {
        npm run build:win-ia32
        Get-ChildItem output
        Copy-Item "output\${PACKAGE_NAME} Setup ${PACKAGE_VERSION}.exe" "releases\${RELEASE}-win-ia32.exe"
      }

test: off

# Packaging artifacts
# https://www.appveyor.com/docs/packaging-artifacts
artifacts:
  # pushing all *.exe files in a directory
  - path: releases\*.exe

# Publishing artifacts to GitHub Releases
# https://www.appveyor.com/docs/deployment/github
deploy:
  - provider: GitHub
    auth_token:
      secure: HJyWcgJc5e5ltkNY7zTUnuuGldoVv3SYJTRXTzrV/RnmMVwYqy6rnNagSRbZtnJZ
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true  # deploy on tag push only
      nodejs_version: "10"
