export const ACTION_UPDATE_STATE = 'ACTION_UPDATE_STATE';
export const ACTION_RESET_CALCULATED_STATE = 'ACTION_RESET_CALCULATED_STATE';

export const ACTION_UPDATE_TRANSFORMATION = 'ACTION_UPDATE_TRANSFORMATION';
export const ACTION_UPDATE_GCODE_CONFIG = 'ACTION_UPDATE_GCODE_CONFIG';
export const ACTION_UPDATE_CONFIG = 'ACTION_UPDATE_CONFIG';
