import React, { PureComponent } from 'react';
import { connect } from 'react-redux';
import Slider from 'rc-slider';
import classNames from 'classnames';
import PropTypes from 'prop-types';
import i18n from '../../../lib/i18n';
import { BOUND_SIZE } from '../../../constants';
import { NumberInput as Input } from '../../../components/Input';
import controller from '../../../lib/controller';
import styles from '.././styles.styl';
import { actions } from '../../../reducers/workspace';
import PrintTracePreview from './PrintTracePreview';


function generateSquareGcode(sideLength, power) {
    // M3: laser on
    // M5: laser off
    const gcodeArray = [];
    const p0 = {
        x: (BOUND_SIZE - sideLength) / 2,
        y: (BOUND_SIZE - sideLength) / 2
    };
    const p1 = {
        x: p0.x + sideLength,
        y: p0.y
    };
    const p2 = {
        x: p0.x + sideLength,
        y: p0.y + sideLength
    };
    const p3 = {
        x: p0.x,
        y: p0.y + sideLength
    };
    // power in percentage
    // priority: P > S, for compatibility, use both P and S args.
    const powerStrength = Math.floor(power * 255 / 100);
    const workSpeed = 1500;

    gcodeArray.push(';Laser Square G-code Generated by Snapmakerjs.');
    gcodeArray.push(';powerPercent: ' + power);
    gcodeArray.push(';workSpeed: ' + workSpeed);

    gcodeArray.push('M5'); // Turn off laser if it's turned on

    // move x&y to zero
    gcodeArray.push('G91'); // relative position
    gcodeArray.push(`G0 X${-BOUND_SIZE - 10} F400`);
    gcodeArray.push('G0 X8');
    gcodeArray.push(`G0 Y${-BOUND_SIZE - 10} F400`);
    gcodeArray.push('G0 Y2');

    gcodeArray.push(`G0 F${workSpeed}`);
    gcodeArray.push(`G1 F${workSpeed}`);

    gcodeArray.push('G90'); // absolute position
    gcodeArray.push('G21'); // set units to mm
    gcodeArray.push('G92 X0 Y0'); // set work origin

    gcodeArray.push(`G0 X${p0.x} Y${p0.y}`);
    // set M3 power
    gcodeArray.push(`M3 P${power} S${powerStrength}`);
    gcodeArray.push(`G1 X${p0.x} Y${p0.y}`);
    gcodeArray.push(`G1 X${p1.x} Y${p1.y}`);
    gcodeArray.push(`G1 X${p2.x} Y${p2.y}`);
    gcodeArray.push(`G1 X${p3.x} Y${p3.y}`);
    gcodeArray.push(`G1 X${p0.x} Y${p0.y}`);
    gcodeArray.push('M5');
    // Push plate out & move laser head to left for taking photo
    gcodeArray.push(`G0 X0 Y${BOUND_SIZE}`);
    return gcodeArray.join('\n') + '\n';
}


class PrintBgImg extends PureComponent {
    static propTypes = {
        addGcode: PropTypes.func.isRequired,
        clearGcode: PropTypes.func.isRequired,
        state: PropTypes.shape({
            sideLength: PropTypes.number.isRequired
        }),
        actions: PropTypes.shape({
            changeSideLength: PropTypes.func.isRequired,
            checkConnectionStatus: PropTypes.func.isRequired
        })
    };

    state = {
        sideLength: 100,
        power: 68
    };

    actions = {
        setSideLength: (sideLength) => {
            this.setState({ sideLength });
        },
        setPower: (power) => {
            this.setState({ power });
        },
        printSquareTrace: () => {
            if (!this.props.actions.checkConnectionStatus()) {
                return;
            }
            const { sideLength, power } = this.state;
            this.props.actions.changeSideLength(sideLength);

            const gcodeStr = generateSquareGcode(sideLength, power);
            this.props.clearGcode();
            this.props.addGcode('Laser Coordinating G-code', gcodeStr);

            setTimeout(() => {
                controller.command('gcode:start');
            }, 1000);
        }
    };

    render() {
        const actions = { ...this.props.actions, ...this.actions };
        const state = { ...this.props.state, ...this.state };

        return (
            <div>
                <div className="clearfix" />
                <div className={styles['laser-set-background-modal-title']}>
                    {i18n._('Print Square Trace')}
                </div>
                <div style={{ textAlign: 'center' }}>
                    <PrintTracePreview
                        sideLength={this.state.sideLength}
                        width={400}
                        height={400}
                    />
                </div>
                <div style={{ height: '74px', margin: '20px 60px' }}>
                    <table className={styles['parameter-table']}>
                        <tbody>
                            <tr>
                                <td>
                                    {i18n._('Side Length')}
                                </td>
                                <td style={{ width: '50%', paddingRight: '15px' }}>
                                    <Slider
                                        value={state.sideLength}
                                        min={40}
                                        max={120}
                                        onChange={actions.setSideLength}
                                    />
                                </td>
                                <td style={{ width: '48px' }}>
                                    <Input
                                        value={state.sideLength}
                                        min={40}
                                        max={120}
                                        onChange={actions.setSideLength}
                                    />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    {i18n._('Power (%)')}
                                </td>
                                <td style={{ width: '50%', paddingRight: '15px' }}>
                                    <Slider
                                        value={state.power}
                                        min={1}
                                        max={100}
                                        onChange={actions.setPower}
                                    />
                                </td>
                                <td style={{ width: '48px' }}>
                                    <Input
                                        min={1}
                                        max={100}
                                        value={state.power}
                                        onChange={actions.setPower}
                                    />
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div style={{ margin: '20px 60px' }}>
                    <button
                        type="button"
                        className={classNames(styles['btn-large'], styles['btn-primary'])}
                        onClick={actions.printSquareTrace}
                        style={{ width: '40%', float: 'left' }}
                    >
                        {i18n._('Print Square Trace')}
                    </button>
                    <button
                        type="button"
                        className={classNames(styles['btn-large'], styles['btn-primary'])}
                        onClick={actions.displayExtractTrace}
                        style={{ width: '40%', float: 'right' }}
                    >
                        {i18n._('Next')}
                    </button>
                </div>
            </div>
        );
    }
}

const mapDispatchToProps = (dispatch) => ({
    addGcode: (name, gcode, renderMethod) => dispatch(actions.addGcode(name, gcode, renderMethod)),
    clearGcode: () => dispatch(actions.clearGcode())
});


export default connect(null, mapDispatchToProps)(PrintBgImg);

