function generateLaserRulerGcode(power, workSpeed, jogSpeed) {
    const lineSpace = 2;
    const shortLength = 5;
    const longLength = 10;
    const count = 21;
    const zStep = 0.2;
    const gcodeArray = [];

    // TODO M3 S table
    const powerStrength = Math.floor(power * 255 / 100);

    gcodeArray.push(';Laser Focus Test G-code Generated by Snapmakerjs.');
    gcodeArray.push(`;powerPercent: ${power}`);
    gcodeArray.push(`;workSpeed: ${workSpeed}`);
    gcodeArray.push(`;jogSpeed: ${jogSpeed}`);

    gcodeArray.push('G90'); // absolute position
    gcodeArray.push('G21'); // set units to mm

    gcodeArray.push(`G0 F${jogSpeed}`);
    gcodeArray.push(`G1 F${workSpeed}`);
    gcodeArray.push('G0 X0 Y0');
    gcodeArray.push(`M3 P${power} S${powerStrength}`);
    gcodeArray.push('M106 P0 S255');
    gcodeArray.push('M5');

    for (let i = 0; i < count; i++) {
        const x = (i - Math.floor(count / 2)) * lineSpace;
        const y = (i % 5) ? shortLength : longLength;
        const z = (i - Math.floor(count / 2)) * zStep;

        gcodeArray.push(`G0 X${x} Y${y} Z${z}`);
        gcodeArray.push(`M3 P${power} S${powerStrength}`);
        gcodeArray.push(`G0 X${x} Y0 Z${z}`);
        gcodeArray.push('M5');
    }
    gcodeArray.push('G0 X0 Y0 Z0');
    gcodeArray.push('M107 P0');
    gcodeArray.push('\n');

    return gcodeArray.join('\n');
}

export default generateLaserRulerGcode;
